### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Dmunch04** [CodeMyst/pastemyst-v2#30]
Any chance you have an idea of the release time?

I've made an API wrapper in Python for the old site, and I can't wait to add the new features from V2.
Or perhaps you have an idea how how the new calls are gonna look like?

Thanks

**Comment by CodeMyst** [comment]
Thank you very much for taking interest in this project! :D

I don't even have any estimate on the time it will take to finish v2, it's a lot bigger than the current one and I started uni so I don't have that much spare time as I used to, but I'll try my best!

I already made sure that the API calls are backwards compatible (if you don't need the new features you don't need to change anything!), but it will all be pretty similar.

Also, can you link your API wrapper (if it's open source of course), if it would be alright with you I'd like to add it to the README.

**Comment by Dmunch04** [comment]
Thanks for your reply!

I see. Just take your time :) After all school is very important.

Also regarding the API. I suppose the way to handle user actions would be with tokens? Also I would love to see API documentation some time soon. Even if there will be changes.

And about my wrapper. It's in very early stages, and is gonna work a lot different once the new site & API will be released. The repo can be found here; https://github.com/Dmunch04/PasteMyst.py

**Comment by CodeMyst** [comment]
I will probably be using GitHub access tokens for user actions, been playing around with it a bit and I think it will work pretty nicely. But I still need to look a lot into security (the plan is that the private pastes are encrypted so that even I can't access them).

And yeah, I will probably start writing some API docs soon as I develop the new version.

Will keep this issue open for now, so if anyone else is wondering about this stuff they can just look here and comment if needed.

**Comment by Dmunch04** [comment]
Alright sounds good. I'll be looking forward to following this and for the API docs!

**Comment by CodeMyst** [comment]
Also, added PasteMyst.py to README.md of the original pastemyst repo.
